- name: Install supporting packages
  apt:
    name:
      - software-properties-common
      - curl
    state: present

- name: Add crio keyring
  shell: |
       curl -fsSL https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/cri-o-apt-keyring.gpg
  register: add_crio_keyring

- name: Debug add_crio_keyring
  debug:
    var: add_crio_keyring.stdout_lines

- name: Add crio repository
  shell: |
        echo "deb [signed-by=/etc/apt/keyrings/cri-o-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/ /" |
        tee /etc/apt/sources.list.d/cri-o.list
  register: add_crio_repo

- name: Debug add_crio_repo
  debug:
    var: add_crio_repo.stdout_lines

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install CRI-O and dependencies
  apt:
    name:
      - cri-o
    state: present
  register: install_crio

- name: Debug install_crio
  debug:
    var: install_crio.stdout_lines

- name: Start and Enable CRI-O service
  systemd:
    name: crio
    state: started
    enabled: yes
  register: start_crio

- name: Debug start_crio
  debug:
    var: start_crio.stdout_lines

- name: Download runc binary using curl
  shell: |
    curl -Lo /tmp/runc-{{ ansible_architecture }} \
      https://github.com/opencontainers/runc/releases/download/v1.3.0/runc-{{ ansible_architecture }}

- name: Install runc binary to /usr/local/sbin/runc
  shell: |
    install -m 755 /tmp/runc-{{ ansible_architecture }} /usr/local/sbin/runc

- name: Download and install CNI plugins
  shell: |
    mkdir -p /opt/cni/bin
    curl -Lo /tmp/cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v1.7.1/cni-plugins-linux-amd64-v1.7.1.tgz
    tar -C /opt/cni/bin -xzf /tmp/cni-plugins.tgz

- name: Validate CNI plugins installation
  stat:
    path: /opt/cni/bin/loopback
  register: loopback_plugin

- name: Fail if CNI plugins are not installed
  fail:
    msg: "CNI plugins installation failed. The 'loopback' plugin is missing in /opt/cni/bin."
  when: not loopback_plugin.stat.exists