- name: Add Kubernetes GPG key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/Release.key | \
      gpg --dearmor | tee /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    warn: false

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ kubernetes_version }}/deb/ /

- name: Install kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni
    state: present
    update_cache: yes
  register: kubernetes_install_result

- name: Debug install result
  debug:
    msg: "Installed packages result: {{ kubernetes_install_result }}"

- name: reinstall missing packages with --reinstall
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni    
    state: present
    update_cache: yes
    force: yes

- name: Hold Kubernetes packages
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Enable kubelet
  systemd:
    name: kubelet
    enabled: yes
    state: started
