- name: Teardown Kubernetes cluster created with kubeadm
  hosts: all
  become: yes
  tasks:
    - name: Drain node (only on master if possible)
      shell: |
        kubectl drain {{ inventory_hostname }} --delete-local-data --force --ignore-daemonsets
      when: inventory_hostname in groups['masters']
      ignore_errors: yes

    - name: Delete node from cluster (only on master)
      shell: |
        kubectl delete node {{ inventory_hostname }}
      when: inventory_hostname in groups['masters']
      ignore_errors: yes

    - name: Stop kubelet service
      systemd:
        name: kubelet
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Reset kubeadm
      shell: kubeadm reset -f
      ignore_errors: yes

    - name: Remove CNI configurations
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/cni/net.d
        - /opt/cni
        - /var/lib/cni
        - /var/lib/kubelet
        - /etc/kubernetes
        - /var/lib/etcd
      ignore_errors: yes

    - name: Remove Kubernetes packages
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: absent
        purge: yes

    - name: Remove Kubernetes apt repository
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/apt/sources.list.d/kubernetes.list
        - /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Remove Kubernetes binaries
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/bin/kubeadm
        - /usr/bin/kubectl
        - /usr/bin/kubelet
        - /usr/bin/crictl
        - /usr/bin/etcd
        - /usr/bin/kube-proxy
      ignore_errors: yes

    - name: Clean up iptables
      shell: iptables -F && iptables -t nat -F && iptables -t mangle -F && iptables -X
      ignore_errors: yes

    - name: Remove .kube directory for user (optional)
      file:
        path: /home/{{ ansible_user }}/.kube
        state: absent
      become_user: "{{ ansible_user }}"
      ignore_errors: yes
