# Section 1: Install Containerd, runc, and Dependencies
- name: Add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

- name: Add Docker repository
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    update_cache: yes

- name: Install containerd, runc, and dependencies
  apt:
    name:
      - containerd.io
      - runc
    state: present
    update_cache: yes
  register: containerd_install_result

- name: Debug containerd installation result
  debug:
    msg: "Installed packages result: {{ containerd_install_result }}"

# Section 2: Ensure Configuration Directory Exists
- name: Ensure /etc/containerd directory exists
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'

# Section 3: Generate Containerd Configuration
- name: Generate containerd config if not present
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml

# Section 4: Install CNI Plugins
- name: Download and install CNI plugins
  shell: |
    mkdir -p /opt/cni/bin
    curl -Lo /tmp/cni-plugins.tgz https://github.com/containernetworking/plugins/releases/download/v1.3.0/cni-plugins-linux-amd64-v1.3.0.tgz
    tar -C /opt/cni/bin -xzf /tmp/cni-plugins.tgz

- name: Validate CNI plugins installation
  stat:
    path: /opt/cni/bin/loopback
  register: loopback_plugin

- name: Fail if CNI plugins are not installed
  fail:
    msg: "CNI plugins installation failed. The 'loopback' plugin is missing in /opt/cni/bin."
  when: not loopback_plugin.stat.exists

# Section 5: Enable and Start Containerd Service
- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: restarted

# Section 6: Validate Containerd Installation
- name: Check containerd version
  shell: containerd --version
  register: containerd_version_check
  failed_when: containerd_version_check.rc != 0

- name: Debug containerd version
  debug:
    msg: "Containerd version: {{ containerd_version_check.stdout }}"
