# Section 1: Install Containerd and Dependencies
- name: Install containerd and dependencies
  apt:
    name:
      - containerd
      - apt-transport-https
      - gpg
      - ca-certificates
    state: present
    update_cache: yes
  register: containerd_install_result

- name: Debug containerd installation result
  debug:
    msg: "Installed packages result: {{ containerd_install_result }}"

# Section 2: Ensure Configuration Directory Exists
- name: Ensure /etc/containerd directory exists
  file:
    path: /etc/containerd
    state: directory
    owner: root
    group: root
    mode: '0755'
  register: containerd_dir_result

- name: Debug directory creation result
  debug:
    msg: "Directory creation result: {{ containerd_dir_result }}"

# Section 3: Generate Containerd Configuration
- name: Check if containerd config exists
  stat:
    path: /etc/containerd/config.toml
  register: containerd_config_check

- name: Generate containerd config if not present
  shell: containerd config default > /etc/containerd/config.toml
  when: not containerd_config_check.stat.exists
  register: containerd_config_result

- name: Debug containerd config generation result
  debug:
    msg: "Config generation result: {{ containerd_config_result }}"
  when: not containerd_config_check.stat.exists

# Section 4: Enable and Start Containerd Service
- name: Enable and start containerd service
  systemd:
    name: containerd
    enabled: yes
    state: restarted
  register: containerd_service_result

- name: Debug containerd service result
  debug:
    msg: "Containerd service result: {{ containerd_service_result }}"

# Section 5: Validate Containerd Installation
- name: Check containerd version
  shell: containerd --version
  register: containerd_version_check
  failed_when: containerd_version_check.rc != 0

- name: Debug containerd version
  debug:
    msg: "Containerd version: {{ containerd_version_check.stdout }}"
